trigger: none

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    echo "<html><body><h1>Hello from pipeline</h1></body></html>" > index.html
  displayName: "Generate HTML file"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'index.html'
    ArtifactName: 'HTMLReport'
    publishLocation: 'Container'
